#!/bin/sh

if [ -z "${RDS_USERNAME}" ]; then
    base_postgres_image_default_user='postgres'
    export RDS_USERNAME="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${RDS_USERNAME}:${RDS_PASSWORD}@${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}"

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${RDS_DB_NAME}",
        user="${RDS_USERNAME}",
        password="${RDS_PASSWORD}",
        host="${RDS_HOSTNAME}",
        port="${RDS_PORT}",
    )
except psycopg2.OperationalError as e:
    print(e)
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
