# AWS only

version: '1'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env # la crea elastic beanstalk
      - ./.envs/.prod/.django
    ports:
      - "80:8000"


