# fly.toml app configuration file generated for recoleccion on 2024-05-12T20:01:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recoleccion'
primary_region = 'eze'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  DJANGO_SETTINGS_MODULE='recoleccion.settings'
  DJANGO_SECRET_KEY='bad_secret_key'
  DEBUG='True'
  VALIDATE_X_REAL_IP='False'
  NEURAL_NETWORK_URL='http://red-neuronal:8000/api'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
