version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django.recoleccion:
    build:
      secrets:
        - ssh_private_key
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: vi-recoleccion
    hostname: recoleccion
    depends_on:
      - postgres.recoleccion
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /start

  postgres.recoleccion:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: recoleccion_postgres_local
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5433:5432"

networks:
  default:
      name: vi-network

secrets:
  ssh_private_key:
    file: ~/.ssh/id_ed25519
