# Generated by Django 4.2 on 2023-07-10 23:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                # ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.AutoField(primary_key=True, editable=False, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('dni', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SenateSeat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                # ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.AutoField(primary_key=True, editable=False, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('province', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=150)),
                ('start_of_term', models.DateField()),
                ('end_of_term', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senate_seat', to='recoleccion.person')),
            ],
            options={
                'unique_together': {('person_id', 'start_of_term', 'end_of_term')},
            },
        ),
        migrations.CreateModel(
            name='DeputySeat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                # ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.AutoField(primary_key=True, editable=False, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('deputy_id', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=150)),
                ('party', models.CharField(max_length=150)),
                ('start_of_term', models.DateField()),
                ('end_of_term', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputy_seat', to='recoleccion.person')),
            ],
            options={
                'unique_together': {('person_id', 'start_of_term', 'end_of_term')},
            },
        ),
    ]
