# Generated by Django 4.2 on 2023-07-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputyseat',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senateseat',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
