# Generated by Django 4.2 on 2023-07-04 03:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0002_deputyseat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenateSeat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=150)),
                ('start_of_term', models.DateField()),
                ('end_of_term', models.DateField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senate_seat', to='recoleccion.person')),
            ],
            options={
                'db_table': 'senate_seat',
                'unique_together': {('person_id', 'start_of_term', 'end_of_term')},
            },
        ),
    ]
