# Generated by Django 4.2 on 2023-07-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0003_socialdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputyseat',
            name='deputy_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
