# Generated by Django 4.2 on 2023-07-07 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0004_alter_person_date_of_birth_alter_person_dni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deputyseat',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='senateseat',
            old_name='person_id',
            new_name='person',
        ),
    ]
