# Generated by Django 4.2 on 2023-07-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0005_law'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputyseat',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputy_seats', to='recoleccion.person'),
        ),
        migrations.AlterField(
            model_name='senateseat',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senate_seats', to='recoleccion.person'),
        ),
    ]
