# Generated by Django 4.2 on 2023-07-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0006_alter_deputyseat_person_alter_senateseat_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_seat',
            field=models.CharField(choices=[('SENATOR', 'Senador'), ('DEPUTY', 'Diputado')], max_length=10, null=True),
        ),
    ]
