# Generated by Django 4.2 on 2023-07-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0007_person_last_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deputyseat',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='senateseat',
            name='is_active',
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
