# Generated by Django 4.2 on 2023-07-27 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0010_lawproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='associated_project',
            field=models.ForeignKey(help_text='Proyecto de ley asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated_law', to='recoleccion.lawproject'),
        ),
        migrations.AddField(
            model_name='law',
            name='project_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
