# Generated by Django 4.2 on 2023-07-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0012_alter_lawproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawproject',
            name='status',
            field=models.CharField(choices=[('ORIGIN_CHAMBER_COMISSION', 'En comisiones, cámara de origen'), ('ORIGIN_CHAMBER_SENTENCE', 'Con dictamen de comisiones, cámara de origen'), ('HALF_SANCTION', 'Media sanción'), ('REVISION_CHAMBER_COMISSION', 'En comisiones, cámara revisora'), ('REVISION_CHAMBER_SENTENCE', 'Con dictamen de comisiones, cámara revisora'), ('WITHDRAWN', 'Retirado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], max_length=30, null=True),
        ),
    ]
