# Generated by Django 4.2 on 2023-07-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0013_alter_lawproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawproject',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
