# Generated by Django 4.2 on 2023-07-30 02:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0014_lawproject_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('chamber', models.CharField(choices=[('SENATORS', 'Cámara de Senadores'), ('DEPUTIES', 'Cámara de Diputados')], max_length=10)),
                ('person_name', models.CharField(max_length=100, null=True)),
                ('person_last_name', models.CharField(max_length=100, null=True)),
                ('party', models.CharField(max_length=200, null=True)),
                ('province', models.CharField(max_length=200, null=True)),
                ('vote', models.CharField(choices=[('ABSENT', 'Ausente'), ('ABSTENTION', 'Abstención'), ('NEGATIVE', 'Negativo'), ('POSITIVE', 'Afirmativo'), ('PRESIDENT', 'Presidente')], max_length=15)),
                ('reference', models.CharField(help_text='Reference in case of not finding the project or law', max_length=200, null=True)),
                ('reference_description', models.TextField(null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('law', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recoleccion.law')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recoleccion.person')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recoleccion.lawproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
