# Generated by Django 4.2 on 2023-08-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0015_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawproject',
            name='deputies_file',
        ),
        migrations.RemoveField(
            model_name='lawproject',
            name='deputies_header_file',
        ),
        migrations.RemoveField(
            model_name='lawproject',
            name='senate_file',
        ),
        migrations.RemoveField(
            model_name='lawproject',
            name='senate_header_file',
        ),
        migrations.AddField(
            model_name='lawproject',
            name='deputies_day_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lawproject',
            name='senate_day_order',
            field=models.IntegerField(null=True),
        ),
    ]
