# Generated by Django 4.2 on 2023-08-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0016_remove_lawproject_deputies_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
