# Generated by Django 4.2 on 2023-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0017_vote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('GENERAL', 'General'), ('OTHER', 'Otro')], default='OTHER', max_length=10),
        ),
    ]
