# Generated by Django 4.2 on 2023-08-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0019_personlinking'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawproject',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='lawproject',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
