# Generated by Django 4.2 on 2023-08-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0020_lawproject_link_lawproject_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawproject',
            name='deputies_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lawproject',
            name='deputies_source',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lawproject',
            name='deputies_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lawproject',
            name='senate_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lawproject',
            name='senate_source',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lawproject',
            name='senate_year',
            field=models.IntegerField(null=True),
        ),
    ]
