# Generated by Django 4.2 on 2023-08-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0021_lawproject_deputies_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawproject',
            name='deputies_project_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lawproject',
            name='senate_project_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lawproject',
            unique_together={('deputies_project_id', 'senate_project_id')},
        ),
    ]
