# Generated by Django 4.2 on 2023-08-19 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recoleccion", "0022_alter_lawproject_deputies_project_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="law",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="recoleccion.law"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="person",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="recoleccion.person"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="recoleccion.lawproject",
            ),
        ),
        migrations.AlterField(
            model_name="law",
            name="initial_file",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
