# Generated by Django 4.2 on 2023-08-26 01:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0023_alter_vote_law_alter_vote_person_alter_vote_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reference', models.CharField(help_text='In case the law project is not found', max_length=150, null=True)),
                ('person_name', models.CharField(max_length=150)),
                ('person_last_name', models.CharField(max_length=150)),
                ('party', models.CharField(max_length=150)),
                ('author_type', models.CharField(choices=[('SENATOR', 'Senador'), ('DEPUTY', 'Diputado')], max_length=10)),
                ('source', models.CharField(max_length=150)),
                ('law_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='recoleccion.lawproject')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='recoleccion.person')),
            ],
            options={
                'unique_together': {('law_project', 'person')},
            },
        ),
    ]
