# Generated by Django 4.2 on 2023-09-02 22:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0024_authorship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('main_denomination', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='deputyseat',
            old_name='party',
            new_name='party_name',
        ),
        migrations.RenameField(
            model_name='senateseat',
            old_name='party',
            new_name='party_name',
        ),
        migrations.CreateModel(
            name='PartyDenomination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('denomination', models.CharField(max_length=200)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='recoleccion.party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
