# Generated by Django 4.2 on 2023-09-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0025_party_rename_party_deputyseat_party_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputyseat',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deputy_seats', to='recoleccion.party'),
        ),
        migrations.AddField(
            model_name='senateseat',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senate_seats', to='recoleccion.party'),
        ),
    ]
