# Generated by Django 4.2 on 2023-09-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0026_deputyseat_party_senateseat_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='partydenomination',
            name='relation_type',
            field=models.CharField(choices=[('ALTERNATIVE_DENOMINATION', 'Denominación alternativa'), ('SUB_PARTY', 'Sub partido')], default='ALTERNATIVE_DENOMINATION', max_length=50),
        ),
    ]
