# Generated by Django 4.2 on 2023-09-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recoleccion", "0027_partydenomination_relation_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="party",
            new_name="party_name",
        ),
        migrations.AddField(
            model_name="vote",
            name="party",
            field=models.ForeignKey(
                null=True, on_delete=models.deletion.CASCADE, related_name="votes", to="recoleccion.party"
            ),
        ),
    ]
