# Generated by Django 4.2 on 2023-09-07 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0029_partylinking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partylinking',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linking', to='recoleccion.party'),
        ),
        migrations.AlterField(
            model_name='personlinking',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linking', to='recoleccion.person'),
        ),
    ]
