# Generated by Django 4.2 on 2023-09-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0030_alter_partylinking_party_alter_personlinking_person'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partydenomination',
            unique_together={('party', 'denomination')},
        ),
    ]
