# Generated by Django 4.2 on 2023-09-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0030_alter_partylinking_party_alter_personlinking_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partydenomination',
            name='denomination',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
