# Generated by Django 4.2 on 2023-10-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0032_rename_party_authorship_party_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorship',
            old_name='law_project',
            new_name='project',
        ),
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together={('project', 'person')},
        ),
    ]
