# Generated by Django 4.2 on 2023-11-20 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0033_rename_law_project_authorship_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('class_name', models.CharField(max_length=200)),
                ('record_value', models.IntegerField(help_text='Year/page/period that is missing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
