# Generated by Django 4.2 on 2023-12-01 00:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0034_missingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkingDecision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('linking_id', models.IntegerField(null=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Aprobado'), ('DENIED', 'Denegado'), ('PENDING', 'Pendiente')], default='PENDING', max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='personlinking',
            name='person',
        ),
        migrations.AddField(
            model_name='authorship',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deputyseat',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lawproject',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='missingrecord',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partydenomination',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='senateseat',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='socialdata',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='linking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='PartyLinkingDecision',
            fields=[
                ('linkingdecision_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recoleccion.linkingdecision')),
                ('messy_denomination', models.CharField(help_text='Messy denomination', max_length=255, null=True)),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linking', to='recoleccion.party')),
            ],
            options={
                'abstract': False,
            },
            bases=('recoleccion.linkingdecision',),
        ),
        migrations.CreateModel(
            name='PersonLinkingDecision',
            fields=[
                ('linkingdecision_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recoleccion.linkingdecision')),
                ('messy_name', models.CharField(help_text='Messy full name', max_length=255, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linking', to='recoleccion.person')),
            ],
            options={
                'abstract': False,
            },
            bases=('recoleccion.linkingdecision',),
        ),
        migrations.DeleteModel(
            name='PartyLinking',
        ),
        migrations.DeleteModel(
            name='PersonLinking',
        ),
    ]
