# Generated by Django 4.2 on 2023-12-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0035_partylinkingdecision_personlinkingdecision_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partylinkingdecision',
            unique_together={('party', 'messy_denomination')},
        ),
        migrations.AlterUniqueTogether(
            name='personlinkingdecision',
            unique_together={('person', 'messy_name')},
        ),
    ]
