# Generated by Django 4.2 on 2024-01-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0037_affidavitentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
