# Generated by Django 4.2 on 2024-01-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0037_affidavitentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawproject',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
