# Generated by Django 4.2 on 2024-01-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0040_law_formatted_lawproject_formatted'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='ai_generated_summary',
            field=models.TextField(null=True),
        ),
    ]
