# Generated by Django 4.2 on 2024-01-10 01:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0041_law_ai_generated_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredNews',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('linking_id', models.UUIDField(editable=False, null=True)),
                ('title', models.TextField(null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
                ('video_url', models.CharField(max_length=1000, null=True)),
                ('image_url', models.CharField(max_length=1000, null=True)),
                ('pubDate', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('source_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
