# Generated by Django 4.2 on 2024-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0042_storednews'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='news_search_terms',
            field=models.CharField(help_text='Search terms for news API', max_length=200, null=True),
        ),
    ]
