# Generated by Django 4.2 on 2024-01-21 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0043_person_news_search_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialdata',
            name='person_last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialdata',
            name='person_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialdata',
            name='picture_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='socialdata',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_data', to='recoleccion.person'),
        ),
    ]
