# Generated by Django 4.2 on 2024-01-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0046_alter_lawproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputyseat',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='missingrecord',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='partydenomination',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='partylinkingdecision',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personlinkingdecision',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='senateseat',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='socialdata',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='storednews',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='affidavitentry',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lawproject',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='source',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
