# Generated by Django 4.2 on 2024-03-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0048_person_last_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
