from django.db import models


class Provinces(models.TextChoices):
    CABA = "CIUDAD AUTONOMA DE BUENOS AIRES", "Ciudad Autónoma de Buenos Aires"
    BUENOS_AIRES = "BUENOS AIRES", "Buenos Aires"
    CATAMARCA = "CATAMARCA", "Catamarca"
    CHACO = "CHACO", "Chaco"
    CHUBUT = "CHUBUT", "Chubut"
    CORDOBA = "CORDOBA", "Córdoba"
    CORRIENTES = "CORRIENTES", "Corrientes"
    ENTRE_RIOS = "ENTRE RIOS", "Entre Ríos"
    FORMOSA = "FORMOSA", "Formosa"
    JUJUY = "JUJUY", "Jujuy"
    LA_PAMPA = "LA PAMPA", "La Pampa"
    LA_RIOJA = "LA RIOJA", "La Rioja"
    MENDOZA = "MENDOZA", "Mendoza"
    MISIONES = "MISIONES", "Misiones"
    TIERRA_DEL_FUEGO = "TIERRA DEL FUEGO", "Tierra del Fuego"
    SANTA_FE = "SANTA FE", "Santa Fe"
    SALTA = "SALTA", "Salta"
    SAN_JUAN = "SAN JUAN", "San Juan"
    SAN_LUIS = "SAN LUIS", "San Luis"
    SANTA_CRUZ = "SANTA CRUZ", "Santa Cruz"
    SANTIAGO_DEL_ESTERO = "SANTIAGO DEL ESTERO", "Santiago del Estero"
    TUCUMAN = "TUCUMAN", "Tucumán"
    RIO_NEGRO = "RIO NEGRO", "Río Negro"
    NEUQUEN = "NEUQUEN", "Neuquén"
