name: Build and Deploy

on:
  push:
    branches:
      - docker

env:
  AWS_REGION: us-east-1
  DOCKER_IMAGE_NAME: your-docker-image-name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE_NAME .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag vi-informacion andy912/vota-informado-recoleccion
          docker push andy912/vota-informado-recoleccion

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name vota-informado-recoleccion \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket=s3://elasticbeanstalk-sa-east-1-344229115324,S3Key=vi-reco.zip

          aws elasticbeanstalk update-environment \
            --application-name vota-informado-recoleccion \
            --environment-name vi-recoleccion-env \
            --version-label $GITHUB_SHA
